import type { MapEdge } from './types';

type Relation = [from: string, to: string, reason: string];
// Editorial recommendations, not official INEP requirements or battle locks.
const before: Relation[] = [
  ['water-minerals', 'membrane-transport', 'Água, solutos e íons ajudam a explicar gradientes e osmose.'],
  ['biomolecules', 'membrane-transport', 'Lipídios e proteínas explicam a estrutura seletiva da membrana.'],
  ['cytology', 'membrane-transport', 'Identificar a membrana e os compartimentos celulares dá contexto às trocas.'],
  ['cytology', 'cell-division', 'Núcleo e cromossomos são referências para acompanhar a divisão.'],
  ['cytology', 'dna-proteins', 'Localizar o material genético e os ribossomos ajuda a acompanhar a síntese.'],
  ['biomolecules', 'dna-proteins', 'Ácidos nucleicos e proteínas são as moléculas envolvidas na expressão gênica.'],
  ['biomolecules', 'cell-metabolism', 'Proteínas, enzimas e moléculas energéticas dão sentido às reações celulares.'],
  ['cytology', 'cell-metabolism', 'A organização celular ajuda a localizar e relacionar os processos metabólicos.'],
  ['cell-metabolism', 'photosynthesis', 'Enzimas e transferências de energia são a base para estudar essas vias.'],
  ['cytology', 'tissues', 'Entender células permite comparar sua especialização nos tecidos.'],
  ['cytology', 'cell-origin', 'Comparar procariontes, eucariontes e organelas ajuda a avaliar a endossimbiose.'],
  ['dna-proteins', 'biotechnology', 'Manipular e identificar DNA exige compreender informação genética.'],
  ['cell-division', 'biotechnology', 'Divisão e diferenciação ajudam a entender clonagem e células-tronco.'],
  ['dna-proteins', 'genetics', 'Genes e alelos ganham significado quando associados ao DNA.'],
  ['cell-division', 'genetics', 'A meiose explica a separação de alelos e a formação dos gametas.'],
  ['genetics', 'immunity', 'A herança ajuda a explicar a expressão dos grupos sanguíneos.'],
  ['biomolecules', 'immunity', 'Reconhecimento molecular ajuda a compreender antígenos e anticorpos.'],
  ['cell-division', 'cancer', 'O controle da divisão é uma base para compreender neoplasias.'],
  ['dna-proteins', 'mutations', 'Conhecer DNA e expressão gênica ajuda a compreender efeitos das mutações.'],
  ['genetics', 'mutations', 'Herança e variabilidade sustentam a interpretação do aconselhamento genético.'],
  ['mutations', 'cancer', 'Alterações genéticas podem modificar o controle da proliferação celular.'],
  ['genetics', 'population-genetics', 'É preciso relacionar herança e alelos antes de estudar sua variação em populações.'],
  ['living-beings', 'taxonomy', 'Comparar grupos e características fornece material para classificá-los.'],
  ['evolution', 'taxonomy', 'Parentesco evolutivo sustenta a leitura de árvores e classificações filogenéticas.'],
  ['cell-division', 'life-cycles', 'Mitose, meiose e fecundação explicam a alternância das fases dos ciclos.'],
  ['living-beings', 'comparative-biology', 'Tipos de organização e nutrição ajudam a comparar funções vitais.'],
  ['tissues', 'embryology', 'Diferenciação celular e organização tecidual ajudam a compreender o desenvolvimento.'],
  ['cell-division', 'embryology', 'As primeiras etapas do desenvolvimento envolvem sucessivas divisões.'],
  ['tissues', 'human-physiology', 'A estrutura dos tecidos ajuda a explicar as funções dos órgãos.'],
  ['membrane-transport', 'human-physiology', 'Trocas pela membrana fundamentam absorção, excreção e equilíbrio interno.'],
  ['evolution', 'human-evolution', 'Seleção, ancestralidade e evidências evolutivas orientam o estudo da linhagem humana.'],
  ['ecosystems', 'ecology', 'Produtores, consumidores e fatores ambientais dão contexto às cadeias e ciclos.'],
  ['ecosystems', 'populations', 'Habitat, nicho e recursos ajudam a compreender interações e crescimento.'],
  ['populations', 'succession', 'Mudanças nas interações e populações ajudam a explicar a sucessão.'],
  ['ecosystems', 'biomes', 'Relacionar fatores bióticos e abióticos permite comparar ambientes.'],
  ['ecology', 'environmental-impacts', 'Fluxos de matéria e energia ajudam a rastrear os efeitos de perturbações.'],
  ['environmental-impacts', 'conservation', 'Reconhecer causas e efeitos dos impactos ajuda a avaliar intervenções.'],
  ['conservation', 'environmental-law', 'As estratégias de proteção dão contexto ao papel da legislação.'],
  ['biology-methods', 'origin-life', 'Hipóteses e evidências permitem comparar explicações sobre a origem da vida.'],
  ['biology-methods', 'evolution', 'A leitura de evidências permite avaliar as teorias evolutivas.'],
  ['population-genetics', 'artificial-selection', 'Variabilidade herdável ajuda a compreender a seleção feita por seres humanos.'],
  ['evolution', 'artificial-selection', 'O conceito de seleção permite comparar seus mecanismos naturais e artificiais.'],
  ['living-beings', 'disease-prevention', 'Conhecer grupos de seres vivos ajuda a diferenciar agentes e vetores.'],
  ['immunity', 'disease-prevention', 'Defesas e memória imunológica ajudam a interpretar vacinação e prevenção.'],
  ['human-physiology', 'social-health', 'O funcionamento do organismo ajuda a analisar consequências biológicas de hábitos e contextos sociais.'],
  ['health-indicators', 'social-health', 'Indicadores evitam reduzir questões coletivas de saúde a escolhas individuais.'],
  ['human-physiology', 'healthy-life', 'Compreender funções do corpo ajuda a avaliar exercício e cuidados com a saúde.'],
  ['measurements', 'graphs-vectors', 'Unidades e grandezas dão significado a eixos, escalas e vetores.'],
  ['graphs-vectors', 'kinematics', 'Gráficos e vetores ajudam a descrever posição, velocidade e aceleração.'],
  ['kinematics', 'newton-laws', 'Velocidade e aceleração permitem explicar como forças alteram movimentos.'],
  ['newton-laws', 'forces', 'As leis do movimento orientam a identificação da força resultante.'],
  ['forces', 'momentum', 'Resultante e tempo de atuação ajudam a compreender impulso.'],
  ['forces', 'statics', 'Diagramas de forças são a base para analisar equilíbrio e torque.'],
  ['forces', 'circular-motion', 'É preciso identificar a resultante que muda a direção da velocidade.'],
  ['forces', 'hydrostatics', 'Força, peso e equilíbrio dão sentido à pressão e à flutuação.'],
  ['forces', 'work-power', 'Força e deslocamento fundamentam o cálculo e a interpretação do trabalho.'],
  ['work-power', 'mechanical-energy', 'Trabalho como transferência de energia ajuda a compreender conservação e dissipação.'],
  ['newton-laws', 'gravitation', 'Força, massa e aceleração ajudam a interpretar a interação gravitacional.'],
  ['gravitation', 'astronomy', 'A atração gravitacional permite explicar órbitas e marés.'],
  ['circular-motion', 'astronomy', 'Movimentos orbitais podem ser estudados a partir de acelerações dirigidas ao centro.'],
  ['graphs-vectors', 'electrostatics', 'Vetores e grandezas ajudam a representar forças e campos.'],
  ['electrostatics', 'electric-current', 'Carga e diferença de potencial dão significado à corrente elétrica.'],
  ['electric-current', 'circuits', 'Tensão, corrente e resistência são as grandezas centrais dos circuitos.'],
  ['circuits', 'electric-power', 'As relações do circuito ajudam a calcular potência e consumo.'],
  ['work-power', 'electric-power', 'Energia e potência ajudam a distinguir consumo de rapidez de transferência.'],
  ['graphs-vectors', 'magnetism', 'Representações vetoriais ajudam a interpretar linhas de campo.'],
  ['kinematics', 'waves', 'Velocidade e periodicidade ajudam a descrever a propagação das ondas.'],
  ['waves', 'wave-phenomena', 'Frequência, comprimento de onda e meios de propagação fundamentam esses fenômenos.'],
  ['wave-phenomena', 'optics', 'Reflexão e refração ajudam a compreender a formação de imagens.'],
  ['measurements', 'temperature', 'Unidades e escalas são úteis para medir e comparar temperaturas.'],
  ['temperature', 'calorimetry', 'Distinguir calor de temperatura permite interpretar trocas térmicas.'],
  ['calorimetry', 'thermodynamics', 'Trocas térmicas e mudanças de estado ajudam a analisar sistemas e máquinas.'],
  ['work-power', 'thermodynamics', 'Máquinas térmicas envolvem transferências de energia por calor e trabalho.'],
  ['materials', 'chemical-changes', 'Distinguir substâncias e misturas ajuda a reconhecer transformações.'],
  ['atomic-models', 'periodic-table', 'A estrutura atômica fundamenta a identificação e organização dos elementos.'],
  ['periodic-table', 'chemical-equations', 'Elementos e fórmulas permitem representar os participantes de uma reação.'],
  ['chemical-changes', 'chemical-equations', 'Reconhecer reagentes e produtos dá sentido às equações.'],
  ['chemical-equations', 'chemical-laws', 'Equações e composição ajudam a relacionar as massas em uma transformação.'],
  ['periodic-table', 'mole', 'Massas atômicas e fórmulas permitem determinar a massa molar.'],
  ['mole', 'stoichiometry', 'O mol permite relacionar proporções de partículas a quantidades macroscópicas.'],
  ['chemical-equations', 'stoichiometry', 'Coeficientes de uma equação balanceada fornecem as proporções da reação.'],
  ['mole', 'gases', 'Quantidade de matéria conecta as relações macroscópicas ao número de partículas.'],
  ['temperature', 'gases', 'Temperatura e escalas absolutas são necessárias para interpretar as leis dos gases.'],
  ['periodic-table', 'metallic-bonds', 'A organização eletrônica ajuda a compreender as ligações nos metais.'],
  ['periodic-table', 'ionic-bonds', 'Elétrons e íons dão sentido às interações em sólidos iônicos.'],
  ['periodic-table', 'covalent-bonds', 'A estrutura eletrônica ajuda a interpretar o compartilhamento de elétrons.'],
  ['covalent-bonds', 'polarity', 'Ligações e geometria molecular ajudam a determinar a distribuição de cargas.'],
  ['polarity', 'water-chemistry', 'Polaridade e interações intermoleculares explicam propriedades da água.'],
  ['materials', 'solutions', 'Misturas homogêneas e heterogêneas são a base para distinguir soluções e dispersões.'],
  ['mole', 'solutions', 'Quantidade de matéria ajuda a interpretar a concentração molar.'],
  ['solutions', 'colligative', 'Quantidade de partículas dissolvidas explica as alterações nas propriedades do solvente.'],
  ['ionic-bonds', 'inorganic-functions', 'Íons e cargas ajudam a formular sais e compreender ácidos e bases em água.'],
  ['inorganic-functions', 'acid-base-reactions', 'Reconhecer as funções inorgânicas ajuda a interpretar neutralização e indicadores.'],
  ['chemical-equations', 'thermochemistry', 'A equação identifica a transformação à qual a variação de entalpia se refere.'],
  ['calorimetry', 'thermochemistry', 'Trocas de calor dão contexto à energia liberada ou absorvida em reações.'],
  ['periodic-table', 'redox', 'Íons e elétrons são a base para acompanhar oxidação e redução.'],
  ['redox', 'electrochemistry', 'Pilhas e eletrólise envolvem transferências de elétrons.'],
  ['electric-current', 'electrochemistry', 'Corrente, carga e tempo ajudam a relacionar o circuito às leis de Faraday.'],
  ['periodic-table', 'radioactivity', 'Núcleo, isótopos e números atômicos são necessários para interpretar transformações nucleares.'],
  ['chemical-changes', 'kinetics', 'É preciso identificar uma transformação antes de acompanhar sua velocidade.'],
  ['kinetics', 'reaction-factors', 'Velocidade e energia de ativação ajudam a explicar os efeitos dos fatores de reação.'],
  ['solutions', 'chemical-equilibrium', 'Concentrações permitem descrever quantitativamente sistemas em equilíbrio.'],
  ['kinetics', 'chemical-equilibrium', 'O equilíbrio dinâmico envolve taxas iguais das reações direta e inversa.'],
  ['chemical-equilibrium', 'ph-hydrolysis', 'O equilíbrio químico fundamenta a análise de ácidos, bases e sais em água.'],
  ['inorganic-functions', 'ph-hydrolysis', 'Reconhecer ácidos, bases e sais ajuda a interpretar pH e hidrólise.'],
  ['chemical-equilibrium', 'equilibrium-shifts', 'A composição de equilíbrio é a referência para avaliar mudanças no sistema.'],
  ['covalent-bonds', 'organic-chemistry', 'O carbono forma estruturas que podem ser entendidas por ligações covalentes.'],
  ['organic-chemistry', 'fermentation', 'Reconhecer funções orgânicas ajuda a acompanhar reagentes e produtos da fermentação.'],
  ['organic-chemistry', 'polymers', 'Estruturas de monômeros ajudam a compreender macromoléculas e materiais poliméricos.'],
  ['organic-chemistry', 'biochemistry-materials', 'Grupos funcionais ajudam a relacionar estrutura e propriedades dessas moléculas.'],
  ['polarity', 'biochemistry-materials', 'Interações com água ajudam a explicar lipídios, sabões e detergentes.'],
  ['chemical-changes', 'everyday-chemistry', 'Reconhecer transformações ajuda a interpretar processos de alimentos, agricultura e saúde.'],
  ['stoichiometry', 'chemical-industry', 'Balanços de matéria ajudam a analisar processos de produção.'],
  ['equilibrium-shifts', 'chemical-industry', 'Condições de equilíbrio ajudam a entender escolhas em processos como a produção de amônia.'],
  ['redox', 'mining', 'Transformações de minerais em metais frequentemente envolvem redução.'],
  ['materials', 'water-treatment', 'Separação de misturas ajuda a entender etapas de tratamento da água.'],
  ['solutions', 'water-treatment', 'Concentração e solubilidade ajudam a avaliar contaminantes e tratamentos.'],
  ['organic-chemistry', 'fossil-fuels', 'Hidrocarbonetos dão contexto à composição e aos usos dos combustíveis fósseis.'],
  ['thermochemistry', 'fossil-fuels', 'Energia de reação permite comparar o aproveitamento dos combustíveis.'],
  ['thermochemistry', 'biofuels', 'O balanço energético ajuda a discutir o uso da biomassa como combustível.'],
  ['radioactivity', 'nuclear-energy', 'Fissão, decaimento e radioisótopos fundamentam a análise de energia e rejeitos nucleares.'],
];

const related: Relation[] = [
  ['solutions', 'membrane-transport', 'Concentração e osmose conectam as soluções químicas às trocas celulares.'],
  ['water-chemistry', 'water-minerals', 'As propriedades da água ajudam a interpretar suas funções biológicas.'],
  ['colligative', 'membrane-transport', 'A pressão osmótica oferece uma leitura química da osmose celular.'],
  ['biomolecules', 'biochemistry-materials', 'Estrutura química e função biológica são duas formas de estudar as mesmas moléculas.'],
  ['photosynthesis', 'ecology', 'Fotossíntese e respiração participam dos ciclos da matéria e do fluxo de energia.'],
  ['photosynthesis', 'thermochemistry', 'Ambos analisam transformações e transferências de energia em reações.'],
  ['cell-metabolism', 'reaction-factors', 'Enzimas são catalisadores biológicos e sua atividade depende das condições do meio.'],
  ['fermentation', 'cell-metabolism', 'Fermentação conecta vias metabólicas a processos de produção.'],
  ['fermentation', 'biofuels', 'A produção de etanol é uma aplicação da fermentação.'],
  ['polymers', 'biomolecules', 'Proteínas, polissacarídeos e ácidos nucleicos são macromoléculas naturais.'],
  ['ph-hydrolysis', 'human-physiology', 'Condições ácido-base influenciam processos fisiológicos.'],
  ['ph-hydrolysis', 'environmental-impacts', 'O pH ajuda a analisar alterações em águas e solos.'],
  ['water-treatment', 'conservation', 'Saneamento articula processos químicos, saúde e conservação ambiental.'],
  ['fossil-fuels', 'environmental-impacts', 'Emissões e ciclos do carbono relacionam combustíveis ao clima e à poluição.'],
  ['biofuels', 'ecology', 'O balanço ambiental dos biocombustíveis envolve ciclos da matéria e uso do solo.'],
  ['temperature', 'biomes', 'Condições térmicas ajudam a interpretar clima e distribuição de seres vivos.'],
  ['thermodynamics', 'environmental-impacts', 'Transferências de energia ajudam a compreender fenômenos climáticos.'],
  ['gases', 'thermodynamics', 'As mesmas relações entre pressão, volume e temperatura aparecem nas duas disciplinas.'],
  ['calorimetry', 'water-chemistry', 'O calor específico da água ajuda a explicar sua influência térmica no ambiente.'],
  ['optics', 'cytology', 'Instrumentos ópticos permitem observar estruturas celulares.'],
  ['waves', 'human-physiology', 'Ondas ajudam a compreender audição e tecnologias de investigação do corpo.'],
  ['radioactivity', 'biotechnology', 'Radioisótopos têm aplicações de investigação e rastreamento em sistemas biológicos.'],
  ['radioactivity', 'mutations', 'Radiações ionizantes podem causar alterações no material genético.'],
  ['magnetism', 'circuits', 'Eletricidade e magnetismo se encontram no funcionamento de tecnologias.'],
  ['population-genetics', 'evolution', 'A teoria sintética relaciona seleção e mudanças na variabilidade genética.'],
  ['cell-origin', 'origin-life', 'A origem das células se insere na investigação sobre o surgimento da vida.'],
  ['biotechnology', 'artificial-selection', 'Seleção e biotecnologia são intervenções distintas sobre características dos organismos.'],
  ['health-indicators', 'conservation', 'Saneamento e ambiente influenciam indicadores de saúde e desenvolvimento.'],
  ['disease-prevention', 'environmental-impacts', 'Alterações ambientais podem mudar a distribuição de agentes e vetores.'],
  ['environmental-law', 'healthy-life', 'Proteção ambiental e qualidade de vida envolvem direitos e ação coletiva.'],
  ['physical-investigation', 'biology-methods', 'Observações, hipóteses e evidências articulam a investigação nas ciências.'],
  ['physical-investigation', 'chemical-changes', 'Investigar transformações envolve observar, medir e testar explicações.'],
  ['chemical-laws', 'stoichiometry', 'Conservação da matéria e proporções sustentam cálculos de reação.'],
  ['metallic-bonds', 'mining', 'Obtenção e uso de metais se relacionam às propriedades da ligação metálica.'],
  ['astronomy', 'origin-life', 'A história da Terra e do Universo contextualiza as hipóteses de origem da vida.'],
];

export const MAP_EDGES: MapEdge[] = [
  ...before.map(([from, to, reason]): MapEdge => ({ from, to, reason, kind: 'before' })),
  ...related.map(([from, to, reason]): MapEdge => ({ from, to, reason, kind: 'related' })),
];
