import { useState } from 'react';
import { View, useWindowDimensions } from 'react-native';
import { router } from 'expo-router';
import { LockKeyhole, CheckCircle2, BookOpen, RotateCcw } from 'lucide-react-native';
import { useApp } from '@/data/provider';
import { TOPICS, topicById } from '@/content/catalog';
import { isDue, prerequisitesMet } from '@/learning/engine';
import { Button, Card, Eyebrow, Heading, Monster, Page, Pill, Progress, Txt } from '@/ui/primitives';
import { colors as c } from '@/ui/theme';
export default function BestiaryScreen() {
  const { state } = useApp(); const { width } = useWindowDimensions(); const columns = width >= 1300 ? 4 : width >= 650 ? 2 : 1;
  const [filter, setFilter] = useState('Todos');
  const known = Object.values(state.masteries).filter(m => m.encountered).length;
  return <Page><View style={{ gap: 10 }}><Eyebrow>SUAS PEQUENAS GRANDES CONQUISTAS</Eyebrow><Heading size={39}>Meu bestiário.</Heading><Txt color={c.muted}>Cada monstro conta uma parte do que você já enfrentou.</Txt></View><Card style={{ backgroundColor: c.purple, borderColor: c.purple, flexDirection: 'row', alignItems: 'center', gap: 24 }}><BookOpen color={c.green} size={35} /><View style={{ flex: 1, gap: 5 }}><Txt weight="heading" size={23} color="#FFFFFF">{known} de 4 monstros conhecidos</Txt><Txt size={13} color="#DED2EC">Conquistar é aprender. Revisitar é fazer ficar.</Txt></View><Txt size={32} color={c.green} weight="heading">{Math.round(known / 4 * 100)}%</Txt></Card><View style={{ flexDirection: 'row', gap: 10, flexWrap: 'wrap' }}>{['Todos', 'Matemática', 'Biologia'].map(f => <Button key={f} title={f} variant={filter === f ? 'primary' : 'secondary'} icon={<></>} onPress={() => setFilter(f)} />)}</View><View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 18 }}>{TOPICS.filter(t => filter === 'Todos' || t.discipline === filter).map(topic => {
    const m = state.masteries[topic.id]; const due = isDue(m, new Date().toISOString()); const locked = !prerequisitesMet(topic.id, state.masteries);
    const label = !m.encountered ? 'A descobrir' : due || m.stage === 'review' ? 'Revisão' : m.stage === 'mastered' ? 'Dominado' : m.stage === 'consolidating' ? 'Consolidando' : 'Em aprendizagem';
    return <View key={topic.id} style={{ width: columns === 1 ? '100%' : columns === 2 ? '48%' : '23.5%' }}><Card style={{ flex: 1, padding: 20, gap: 15 }}><View style={{ alignItems: 'center', backgroundColor: topic.discipline === 'Biologia' ? c.peach : c.lavender, borderRadius: 17, paddingVertical: 7, position: 'relative' }}><Monster id={topic.id} size={columns === 4 ? 170 : 200} muted={!m.encountered} /><View style={{ position: 'absolute', bottom: 12, right: 12, backgroundColor: '#FFFCF9', padding: 8, borderRadius: 20 }}>{!m.encountered ? <LockKeyhole color={c.purple} size={17} /> : due ? <RotateCcw color={c.purple} size={17} /> : <CheckCircle2 color={c.greenDark} size={17} />}</View></View><Eyebrow>{topic.discipline.toUpperCase()}</Eyebrow><Heading size={22}>{topic.name}</Heading><Pill green={m.stage === 'mastered'}>{label}</Pill><Txt size={12} color={c.muted}>{!m.encountered ? locked ? `Antes, fortaleça ${topicById(topic.prerequisiteIds[0]).name.toLowerCase()}.` : 'Esse encontro vai acontecer no seu momento.' : m.nextReviewAt ? `${due ? 'Hora de reencontrar.' : 'Próximo encontro:'} ${new Date(m.nextReviewAt).toLocaleDateString('pt-BR')}` : 'Você está construindo a base, uma batalha de cada vez.'}</Txt>{m.encountered && <Progress value={m.score} label={`Evidência recente em ${topic.name}`} />}</Card></View>;
  })}</View><Card style={{ backgroundColor: c.peach, flexDirection: 'row', gap: 16 }}><RotateCcw size={22} color={c.purple} /><View style={{ gap: 7, flex: 1 }}><Txt weight="bold" color={c.purple}>Um reencontro não apaga sua conquista.</Txt><Txt size={13} color={c.muted}>Monstros voltam para revisões curtas. Para dominar um conteúdo, você precisa demonstrar o que aprendeu agora e depois de um intervalo.</Txt></View></Card><Button title={state.diagnosticCompletedAt ? 'Voltar ao meu próximo monstro' : 'Começar minha jornada'} onPress={() => router.replace('/')} variant="secondary" /></Page>;
}
