import { useMemo, useState } from 'react';
import { Pressable, View, useWindowDimensions } from 'react-native';
import { router } from 'expo-router';
import { LockKeyhole, CheckCircle2, BookOpen, RotateCcw } from 'lucide-react-native';
import { useApp } from '@/data/provider';
import { calculateRetention, isDue, prerequisitesMet } from '@/learning/engine';
import { Button, Card, Eyebrow, Heading, Monster, Page, Pill, Progress, Txt } from '@/ui/primitives';
import { colors as c } from '@/ui/theme';
export default function BestiaryScreen() {
  const { state, topics, topicById } = useApp(); const { width } = useWindowDimensions(); const columns = width >= 1300 ? 4 : width >= 650 ? 2 : 1;
  const [filter, setFilter] = useState('Todos');
  const total = topics.length;
  const known = topics.filter(t => state.masteries[t.id]?.encountered).length;
  const disciplines = useMemo(() => ['Todos', ...Array.from(new Set(topics.map(t => t.discipline)))], [topics]);
  const now = new Date().toISOString();
  return <Page><View style={{ gap: 10 }}><Eyebrow>SUAS PEQUENAS GRANDES CONQUISTAS</Eyebrow><Heading size={39}>Meu bestiário.</Heading><Txt color={c.muted}>Cada monstro conta uma parte do que você já enfrentou.</Txt></View><Card style={{ backgroundColor: c.purple, borderColor: c.purple, flexDirection: 'row', alignItems: 'center', gap: 24 }}><BookOpen color={c.green} size={35} /><View style={{ flex: 1, gap: 5 }}><Txt weight="heading" size={23} color="#FFFFFF">{known} de {total} monstros conhecidos</Txt><Txt size={13} color="#DED2EC">Conquistar é aprender. Revisitar é fazer ficar.</Txt></View><Txt size={32} color={c.green} weight="heading">{Math.round(known / Math.max(1, total) * 100)}%</Txt></Card><View style={{ flexDirection: 'row', gap: 10, flexWrap: 'wrap' }}>{disciplines.map(f => <Button key={f} title={f} variant={filter === f ? 'primary' : 'secondary'} icon={<></>} onPress={() => setFilter(f)} />)}</View><View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 18 }}>{topics.filter(t => filter === 'Todos' || t.discipline === filter).map(topic => {
    const m = state.masteries[topic.id] ?? { topicId: topic.id, score: 0, evidence: 0, encountered: false, stage: 'unseen', reviewLevel: 0 };
    const due = isDue(m, now);
    const retention = calculateRetention(m, now);
    const locked = !prerequisitesMet(topic.id, state.masteries);
    const prereqTopic = topic.prerequisiteIds.length ? topicById(topic.prerequisiteIds[0]) : null;
    const label = !m.encountered ? 'A descobrir' : due || m.stage === 'review' ? 'Revisão' : m.stage === 'mastered' ? (retention < 0.75 ? 'Revisitar' : 'Dominado') : m.stage === 'consolidating' ? 'Consolidando' : 'Em aprendizagem';
    return <View key={topic.id} style={{ width: columns === 1 ? '100%' : columns === 2 ? '48%' : '23.5%' }}><Pressable accessibilityRole="button" accessibilityLabel={`Conheça o monstro ${topic.name}`} onPress={() => router.push({ pathname: '/monster', params: { topicId: topic.id } } as unknown as Parameters<typeof router.push>[0])} style={({ pressed }) => ({ flex: 1, opacity: pressed ? .82 : 1 })}><Card style={{ flex: 1, padding: 20, gap: 15 }}><View style={{ alignItems: 'center', backgroundColor: topic.discipline === 'Biologia' ? c.peach : c.lavender, borderRadius: 17, paddingVertical: 7, position: 'relative' }}><Monster id={topic.id} size={columns === 4 ? 170 : 200} muted={!m.encountered} /><View style={{ position: 'absolute', bottom: 12, right: 12, backgroundColor: '#FFFCF9', padding: 8, borderRadius: 20 }}>{!m.encountered ? <LockKeyhole color={c.purple} size={17} /> : due ? <RotateCcw color={c.purple} size={17} /> : <CheckCircle2 color={c.greenDark} size={17} />}</View></View><Eyebrow>{topic.discipline.toUpperCase()}</Eyebrow><Heading size={22}>{topic.name}</Heading><Pill green={m.stage === 'mastered' && retention >= 0.75}>{label}</Pill><Txt size={12} color={c.muted}>{!m.encountered ? locked ? `Antes, fortaleça ${prereqTopic?.name.toLowerCase() ?? 'o conteúdo anterior'}.` : 'Esse encontro vai acontecer no seu momento.' : m.nextReviewAt ? `${due ? 'Hora de reencontrar.' : 'Próximo encontro:'} ${new Date(m.nextReviewAt).toLocaleDateString('pt-BR')}` : 'Você está construindo a base, uma batalha de cada vez.'}</Txt>{m.encountered && <View style={{ gap: 5 }}><View style={{ flexDirection: 'row', justifyContent: 'space-between' }}><Txt size={11} color={c.muted}>Retenção da memória</Txt><Txt size={11} weight="bold" color={retention < 0.75 ? c.purple : c.greenDark}>{Math.round(retention * 100)}%</Txt></View><Progress value={retention} label={`Retenção estimada em ${topic.name}`} /></View>}<Txt size={12} weight="bold" color={c.purple}>Conheça seu monstro →</Txt></Card></Pressable></View>;
  })}</View><Card style={{ backgroundColor: c.peach, flexDirection: 'row', gap: 16 }}><RotateCcw size={22} color={c.purple} /><View style={{ gap: 7, flex: 1 }}><Txt weight="bold" color={c.purple}>Um reencontro não apaga sua conquista.</Txt><Txt size={13} color={c.muted}>Monstros voltam para revisões curtas. Para dominar um conteúdo, você precisa demonstrar o que aprendeu agora e depois de um intervalo.</Txt></View></Card><Button title={state.diagnosticCompletedAt ? 'Voltar ao meu próximo monstro' : 'Começar minha jornada'} onPress={() => router.replace('/')} variant="secondary" /></Page>;
}
